version: '3.8'

services:
  app:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
    # We don't map ports here because only Nginx needs to be public

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app

networks:
  default:
    driver: bridge